---
title: Caroline Hollard
baseline: Your blogging assistant
description: Communication culturelle
baseurl: "/public"
canonicalurl: true
keywords:
- Cecil
- Static Site Generator
- SSG
author: Arnaud Ligny
date:
  format: j F Y
  timezone: Europe/Paris
theme:
- hyde
- netlify
- netlify-cms
hyde:
  sidebar:
    sticky: true
  theme: ''
  reverse: true
